import { Link } from 'react-router-dom'
import { Button } from '../ui/button'
import { useGame } from '../contexts/GameContext'
import { Sword, Shield, Users, BookOpen } from 'lucide-react'

/**
 * Home page component - main landing page for the RPG application
 * Provides navigation to character creation and game loading
 */
const HomePage = () => {
  const { gameState, loadGameState } = useGame()
  
  /**
   * Handle loading an existing game session
   */
  const handleLoadGame = async () => {
    try {
      // For demo purposes, using a mock session ID
      // In a real app, this would come from user selection
      await loadGameState('demo-session-123')
    } catch (error) {
      console.error('Failed to load game:', error)
    }
  }
  
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
      {/* Header */}
      <header className="relative overflow-hidden">
        <div className="absolute inset-0 bg-black/20" />
        <div className="relative container mx-auto px-4 py-16 text-center">
          <h1 className="text-6xl font-bold text-white mb-4 drop-shadow-lg">
            Fantasy RPG
          </h1>
          <p className="text-xl text-gray-200 mb-8 max-w-2xl mx-auto">
            Embark on an epic adventure in a world of magic, mystery, and endless possibilities.
            Create your character and forge your own destiny.
          </p>
        </div>
      </header>
      
      {/* Main Content */}
      <main className="container mx-auto px-4 py-12">
        <div className="max-w-4xl mx-auto">
          {/* Game Actions */}
          <div className="grid md:grid-cols-2 gap-8 mb-12">
            {/* New Game */}
            <div className="bg-white/10 backdrop-blur-sm rounded-lg p-8 border border-white/20">
              <div className="flex items-center mb-4">
                <Sword className="w-8 h-8 text-yellow-400 mr-3" />
                <h2 className="text-2xl font-bold text-white">New Adventure</h2>
              </div>
              <p className="text-gray-300 mb-6">
                Create a new character and begin your journey in the fantasy realm.
                Choose your class, customize your appearance, and set forth into the unknown.
              </p>
              <Link to="/character-creation">
                <Button size="lg" className="w-full bg-yellow-600 hover:bg-yellow-700">
                  Create Character
                </Button>
              </Link>
            </div>
            
            {/* Continue Game */}
            <div className="bg-white/10 backdrop-blur-sm rounded-lg p-8 border border-white/20">
              <div className="flex items-center mb-4">
                <Shield className="w-8 h-8 text-blue-400 mr-3" />
                <h2 className="text-2xl font-bold text-white">Continue Journey</h2>
              </div>
              <p className="text-gray-300 mb-6">
                Resume your existing adventure and continue where you left off.
                Your progress and achievements are waiting for you.
              </p>
              {gameState ? (
                <Link to="/game">
                  <Button size="lg" className="w-full bg-blue-600 hover:bg-blue-700">
                    Continue Game
                  </Button>
                </Link>
              ) : (
                <Button 
                  size="lg" 
                  className="w-full bg-blue-600 hover:bg-blue-700"
                  onClick={handleLoadGame}
                >
                  Load Game
                </Button>
              )}
            </div>
          </div>
          
          {/* Features */}
          <div className="grid md:grid-cols-3 gap-6">
            <div className="text-center">
              <div className="bg-white/10 backdrop-blur-sm rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                <Users className="w-8 h-8 text-green-400" />
              </div>
              <h3 className="text-xl font-semibold text-white mb-2">Dynamic NPCs</h3>
              <p className="text-gray-300">
                Interact with intelligent NPCs that remember your actions and develop relationships.
              </p>
            </div>
            
            <div className="text-center">
              <div className="bg-white/10 backdrop-blur-sm rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                <BookOpen className="w-8 h-8 text-purple-400" />
              </div>
              <h3 className="text-xl font-semibold text-white mb-2">AI-Driven Stories</h3>
              <p className="text-gray-300">
                Experience unique narratives generated by advanced AI that adapts to your choices.
              </p>
            </div>
            
            <div className="text-center">
              <div className="bg-white/10 backdrop-blur-sm rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                <Sword className="w-8 h-8 text-red-400" />
              </div>
              <h3 className="text-xl font-semibold text-white mb-2">Epic Quests</h3>
              <p className="text-gray-300">
                Embark on challenging quests with meaningful consequences and rewards.
              </p>
            </div>
          </div>
        </div>
      </main>
      
      {/* Footer */}
      <footer className="container mx-auto px-4 py-8 text-center text-gray-400">
        <p>&copy; 2024 Fantasy RPG. Embark on your adventure today.</p>
      </footer>
    </div>
  )
}

export default HomePage