name: Deploy RPG Fantasy App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build frontend
      run: npm run build
      env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: ${{ secrets.CUSTOM_DOMAIN }}

  health-check:
    runs-on: ubuntu-latest
    needs: deploy-frontend
    steps:
    - name: Health Check Backend
      run: |
        echo "Checking backend health..."
        curl -f ${{ secrets.VITE_API_URL }}/health || echo "Backend health check failed"
    
    - name: Health Check Frontend
      run: |
        echo "Checking frontend deployment..."
        curl -f https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/ || echo "Frontend health check failed"